#! /bin/sh

sxhkd &

bspc monitor HDMI-A-1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DisplayPort-1 -d 11 12 13 14 15 16 17 18 19 20

bspc config border_width         0
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
